# Set all versions
CUSTOM_BUILD_TYPE ?= alpha

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

CUSTOM_PLATFORM_VERSION := 10.0

LOTUS_VERSION_NUMBER := v1.6

TARGET_PRODUCT_SHORT := $(subst lotus_,,$(CUSTOM_BUILD))

CUSTOM_VERSION := LotusOS_$(LOTUS_VERSION_NUMBER)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION_PROP := 10

CUSTOM_PROPERTIES := \
    ro.lotus.version=$(CUSTOM_VERSION_PROP) \
    ro.lotus.version.display=$(CUSTOM_VERSION) \
    ro.lotus.build_date=$(CUSTOM_BUILD_DATE) \
    ro.lotus.build_date_utc=$(CUSTOM_BUILD_DATE_UTC) \
    ro.lotus.build_type=$(CUSTOM_BUILD_TYPE)

ifeq ($(CUSTOM_BUILD_TYPE), OFFICIAL)
PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/secure/releasekey
endif
